#spring:
#  datasource:
#    username: root
#    password: xzlyf297
#    url: jdbc:mysql://192.168.1.107:3306/web_demo?serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.107:3306/app_todolist
    username: root
    password: xzlyf297
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true