logging:
  config: classpath:log4j2.xml
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.166:3306/app_todolist?useUnicode=true&characterEncoding=gbk
    username: root
    password: xzlyf297
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
